import {
    Home,
    ShoppingCart,
    Car,
    Utensils,
    Zap,
    Coffee,
    Gift,
    Music,
    Briefcase,
    DollarSign,
    TrendingUp,
    Smartphone,
    Wifi,
    Tv,
    Dumbbell,
    Book,
    Plane,
    Heart,
    Smile,
    Pizza,
    Gamepad2,
    ShoppingBag,
    Shirt,
    Fuel,
    Bus,
    Train,
    Bike,
    Stethoscope,
    Pill,
    GraduationCap,
    Wrench,
    Hammer,
    PaintBucket,
    Lightbulb,
    Droplet,
    Flame,
    Snowflake,
    Sun,
    Moon,
    Star,
    type LucideIcon,
} from 'lucide-react';

export interface IconItem {
    name: string;
    icon: LucideIcon;
}

export const AVAILABLE_ICONS: IconItem[] = [
    { name: 'Home', icon: Home },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'ShoppingBag', icon: ShoppingBag },
    { name: 'Car', icon: Car },
    { name: 'Bus', icon: Bus },
    { name: 'Train', icon: Train },
    { name: 'Bike', icon: Bike },
    { name: 'Plane', icon: Plane },
    { name: 'Fuel', icon: Fuel },
    { name: 'Utensils', icon: Utensils },
    { name: 'Pizza', icon: Pizza },
    { name: 'Coffee', icon: Coffee },
    { name: 'Zap', icon: Zap },
    { name: 'Lightbulb', icon: Lightbulb },
    { name: 'Wifi', icon: Wifi },
    { name: 'Smartphone', icon: Smartphone },
    { name: 'Tv', icon: Tv },
    { name: 'Gamepad2', icon: Gamepad2 },
    { name: 'Gift', icon: Gift },
    { name: 'Music', icon: Music },
    { name: 'Briefcase', icon: Briefcase },
    { name: 'DollarSign', icon: DollarSign },
    { name: 'TrendingUp', icon: TrendingUp },
    { name: 'Dumbbell', icon: Dumbbell },
    { name: 'Book', icon: Book },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'Heart', icon: Heart },
    { name: 'Stethoscope', icon: Stethoscope },
    { name: 'Pill', icon: Pill },
    { name: 'Smile', icon: Smile },
    { name: 'Shirt', icon: Shirt },
    { name: 'Wrench', icon: Wrench },
    { name: 'Hammer', icon: Hammer },
    { name: 'PaintBucket', icon: PaintBucket },
    { name: 'Droplet', icon: Droplet },
    { name: 'Flame', icon: Flame },
    { name: 'Snowflake', icon: Snowflake },
    { name: 'Sun', icon: Sun },
    { name: 'Moon', icon: Moon },
    { name: 'Star', icon: Star },
];

export function getIconComponent(iconName: string): LucideIcon | null {
    const iconData = AVAILABLE_ICONS.find(i => i.name === iconName);
    return iconData ? iconData.icon : null;
}
