import {
    Home,
    ShoppingCart,
    Car,
    Utensils,
    Zap,
    Coffee,
    Gift,
    Music,
    Briefcase,
    DollarSign,
    TrendingUp,
    Smartphone,
    Wifi,
    Tv,
    Dumbbell,
    Book,
    Plane,
    Heart,
    Smile,
    Pizza,
    Gamepad2,
    ShoppingBag,
    Shirt,
    Fuel,
    Bus,
    Train,
    Bike,
    Stethoscope,
    Pill,
    GraduationCap,
    Wrench,
    Hammer,
    PaintBucket,
    Lightbulb,
    Droplet,
    Flame,
    Snowflake,
    Sun,
    Moon,
    Star,
    Turtle,
    Calendar,
    Tag,
    CheckSquare,
    Receipt,
    Wallet,
    Building2,
    Award,
    FileText,
    Pen,
    Brain,
    Fingerprint,
    Fish,
    Carrot,
    Beer,
    Mountain,
    TreePine,
    Map,
    MapPin,
    Palmtree,
    Hotel,
    Laptop,
    Tablet,
    User,
    Settings,
    Lock,
    Trophy,
    Medal,
    type LucideIcon,
} from 'lucide-react';

export interface IconItem {
    name: string;
    icon: LucideIcon;
}

export const AVAILABLE_ICONS: IconItem[] = [
    { name: 'Home', icon: Home },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'ShoppingBag', icon: ShoppingBag },
    { name: 'Car', icon: Car },
    { name: 'Bus', icon: Bus },
    { name: 'Train', icon: Train },
    { name: 'Bike', icon: Bike },
    { name: 'Plane', icon: Plane },
    { name: 'Fuel', icon: Fuel },
    { name: 'Utensils', icon: Utensils },
    { name: 'Pizza', icon: Pizza },
    { name: 'Coffee', icon: Coffee },
    { name: 'Zap', icon: Zap },
    { name: 'Lightbulb', icon: Lightbulb },
    { name: 'Wifi', icon: Wifi },
    { name: 'Smartphone', icon: Smartphone },
    { name: 'Tv', icon: Tv },
    { name: 'Gamepad2', icon: Gamepad2 },
    { name: 'Gift', icon: Gift },
    { name: 'Music', icon: Music },
    { name: 'Briefcase', icon: Briefcase },
    { name: 'DollarSign', icon: DollarSign },
    { name: 'TrendingUp', icon: TrendingUp },
    { name: 'Dumbbell', icon: Dumbbell },
    { name: 'Book', icon: Book },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'Heart', icon: Heart },
    { name: 'Stethoscope', icon: Stethoscope },
    { name: 'Pill', icon: Pill },
    { name: 'Smile', icon: Smile },
    { name: 'Shirt', icon: Shirt },
    { name: 'Wrench', icon: Wrench },
    { name: 'Hammer', icon: Hammer },
    { name: 'PaintBucket', icon: PaintBucket },
    { name: 'Droplet', icon: Droplet },
    { name: 'Flame', icon: Flame },
    { name: 'Snowflake', icon: Snowflake },
    { name: 'Sun', icon: Sun },
    { name: 'Moon', icon: Moon },
    { name: 'Star', icon: Star },
    { name: 'Turtle', icon: Turtle },
    { name: 'Calendar', icon: Calendar },
    { name: 'Tag', icon: Tag },
    { name: 'CheckSquare', icon: CheckSquare },
    { name: 'Receipt', icon: Receipt },
    { name: 'Wallet', icon: Wallet },
    { name: 'Building2', icon: Building2 }, // Building
    { name: 'Award', icon: Award }, // Certificate
    { name: 'FileText', icon: FileText }, // License
    { name: 'Pen', icon: Pen },
    { name: 'Brain', icon: Brain }, // Cognitive
    { name: 'Fingerprint', icon: Fingerprint },
    { name: 'Fish', icon: Fish },
    { name: 'Carrot', icon: Carrot }, // Corn/Veg
    { name: 'Beer', icon: Beer }, // Bar
    { name: 'Mountain', icon: Mountain },
    { name: 'TreePine', icon: TreePine }, // Tree
    { name: 'Map', icon: Map },
    { name: 'MapPin', icon: MapPin }, // Location
    { name: 'Palmtree', icon: Palmtree },
    { name: 'Hotel', icon: Hotel },
    { name: 'Laptop', icon: Laptop },
    { name: 'Tablet', icon: Tablet },
    { name: 'User', icon: User },
    { name: 'Settings', icon: Settings },
    { name: 'Lock', icon: Lock }, // Password
    { name: 'Trophy', icon: Trophy },
    { name: 'Medal', icon: Medal },
];

export function getIconComponent(iconName: string): LucideIcon | null {
    const iconData = AVAILABLE_ICONS.find(i => i.name === iconName);
    return iconData ? iconData.icon : null;
}
